server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Procorp-homemade-2022-1/Back-end.git
          searchPaths: config-data
          user-name: ${GIT_USER}
          password: ${GIT_PASSWORD}
          default-label: "master"
  security:
    user:
      name: root
      password: s3cr3t


